version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: github-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fullstack-app
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - github-app-network

  redis:
    image: redis:7-alpine
    container_name: github-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - github-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: github-app-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/github_app?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_PORT: 3000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - github-app-network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: github-app-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_FRONTEND_URL: http://localhost:5173
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - github-app-network

volumes:
  postgres-data:
  redis-data:

networks:
  github-app-network:
    driver: bridge

